# Codecov Configuration

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 34%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 50%
        threshold: 5%

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "tools/"
  - "**/__pycache__/"
  - "**/migrations/"
